name: Build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: recursive

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Check changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ./gradlew clean run --args="verbose singleChainCheck $file"
          done

      - name: Declare JAVA_HOME ENV Variable
        run: export JAVA_HOME=$(/usr/libexec/java_home -v 21)

      - name: Build
        run: |
          ./gradlew run

